version: 2
jobs:
  build:
    docker:
      # Update stack.yaml when you change this.
      - image: fpco/stack-build:lts-11.15
    steps:
      - checkout
      - run: stack install hlint
      - run: ./test-template.sh cli
